Suggested Import changes and notes
semanio/airbnb-javascript pull request #4
Opened 2021-05-24 13:57 UTC by zkiektylertech

2021-06-16 18:28 UTC, semanio requested changes

2021-06-16 18:28 UTC, semanio commented on packages/eslint-config-airbnb-base/rules/imports.js
>      'import/prefer-default-export': 'error',
Update this to `off`

2021-06-23 18:33 UTC, zkiektylertech commented on packages/eslint-config-airbnb-base/rules/imports.js
>      'import/prefer-default-export': 'error',
Updated to Off

2021-06-24 19:17 UTC, semanio approved these changes

2021-06-24 19:17 UTC, merged